/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/containers/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"UTM Avo"', 'Arial', 'sans-serif'],
        UTMAVo: ['"UTM Avo"', 'Arial', 'sans-serif'],
        Inter: ['Inter', 'sans-serif'],
        Montserrat: ['Montserrat', 'sans-serif'],
        UTMImpact: ['"UTM Impact"', 'Impact', 'sans-serif'],
      },
      fontSize: {
        'brand-display': ['48px', '58px'],
        'brand-title': ['40px', '48px'],
        'brand-subtitle': ['32px', '40px'],
        'brand-card-title': ['24px', '32px'],
        'brand-body-lg': ['20px', '30px'],
        'brand-body': ['16px', '24px'],
        'brand-caption': ['14px', '20px'],
        'brand-tiny': ['12px', '16px'],
        'marketing-hero': ['clamp(28px, 2.1vw, 40px)', '1.38'],
        'marketing-hero-overlay': ['clamp(22px, 2vw, 38px)', '1.2'],
        'marketing-hero-caption': ['35px', '42px'],
        'marketing-section-lg': ['clamp(28px, 2.25vw, 42px)', '1.15'],
        'marketing-section': ['40px', '48px'],
        'marketing-section-sm': ['30px', '36px'],
        'marketing-control': ['22px', '22px'],
        'marketing-card-heading': ['22px', '28px'],
        'marketing-card-title-lg': ['28px', '1.15'],
        'marketing-card-copy': ['20px', '1.4'],
        'marketing-copy': ['25px', '32px'],
        'marketing-logo-label': ['18px', '24px'],
        'marketing-map-bullet': ['17px', '17px'],
        'marketing-timeline-date': ['19px', '19px'],

        'pb-h1': ['48px', '58px'],
        'pb-h2': ['40px', '48px'],
        'pb-body': ['32px', '40px'],
        'pb-small': ['24px', '32px'],
        'pb-xs': ['14px', '20px'],

        'lp-h1': ['48px', '58px'],
        'lp-h2': ['47px', '58px'],
        'lp-body': ['20px', '30px'],
        'lp-small': ['16px', '24px'],

        'lp-section-title': [
          '47px',
          {
            lineHeight: '58px',
            fontWeight: 800,
          },
        ],
        'lp-section-title-2': [
          '35px',
          {
            lineHeight: '39px',
            fontWeight: 800,
          },
        ],
        'lp-card-title': [
          '24px',
          {
            lineHeight: '32px',
            fontWeight: 700,
          },
        ],
      },
      aspectRatio: {
        'hero-side': '1 / 0.74',
        'hero-main': '1320 / 570',
        'hero-main-mobile': '1 / 0.68',
        video: '940 / 585',
        'about-image': '700 / 360',
        'franchise-top': '450 / 310',
        'service-card': '1 / 0.72',
        'service-model': '680 / 420',
        concept: '420 / 320',
      },
      colors: {
        'sync-primary-color': 'var(--sync-primary-color)',
        'sync-secondary-color': 'var(--sync-secondary-color)',
        'sync-text-color': 'var(--sync-text-color)',
        'sync-button-text-color': 'var(--sync-button-text-color)',
        'sync-button-border-color': 'var(--sync-button-border-color)',
        'sync-input-background-color': 'var(--sync-input-background-color)',
        'sync-title-color': 'var(--sync-title-color)',
        'sync-border-title-1-color': 'var(--sync-border-title-1-color)',
        'sync-border-title-2-color': 'var(--sync-border-title-2-color)',

        'lp-primary-color': 'var(--lp-primary-color)',
        'lp-header-link-color': 'var(--lp-header-link-color)',
        'lp-second-primary-color': 'var(--lp-second-primary-color)',
        'lp-lighter-primary-color': 'var(--lp-lighter-primary-color)',
        'lp-lighter2-primary-color': 'var(--lp-lighter2-primary-color)',
        'lp-secondary-color': 'var(--lp-secondary-color)',
        'lp-gold-color': 'var(--lp-gold-color)',
        'brand-pink': '#f7b5b9',
        'brand-pink-hover': '#ec8e96',
        'brand-text': '#606060',
        'brand-muted': '#bcbec0',
        'brand-page': '#f8f8f8',
        'brand-line': '#d9d9d9',
        'brand-soft-line': '#f4c5ca',
        'brand-mobile-line': '#f5d0d4',
        'brand-control': '#9a9a9a',
        'brand-control-dark': '#8f8f8f',
        'brand-placeholder': '#b8b8b8',
      },
      backgroundImage: {
        'gradient-pink':
          'linear-gradient(to right bottom, white, var(--lp-lighter2-primary-color))',
      },
      zIndex: {
        1: '1',
        'z-index-header': 'var(--z-index-header)',
        'z-index-banner-dot': 'var(--z-index-banner-dot)',
        'z-index-retake-result': 'var(--z-index-retake-result)',
        'z-index-backdrop': 'var(--z-index-backdrop)',
        'z-index-button-on-backdrop': 'var(--z-index-button-on-backdrop)',
        'z-index-freeze-webcam-loading': 'var(--z-index-freeze-webcam-loading)',
        'z-index-loading': 'var(--z-index-loading)',
        'z-index-popup': 'var(--z-index-popup)',
        'z-index-floating-button': 'var(--z-index-floating-button)',
        'z-index-popover': 'var(--z-index-popover)',
      },
      borderWidth: {
        0.2: '2px',
        0.5: '5px',
        1: '10px',
        3: '30px',
        8: '8px',
        14: '14px',
      },
      lineHeight: {
        1.8: '18px',
        4: '40px',
      },
      transitionProperty: {
        right: 'right',
      },
      height: {
        header: '176px',
        'hero-side-panel': '320px',
        'difference-tile': '440px',
        'store-coverage': '1080px',
        'store-map-art': '1080px',
      },
      width: {
        '3/10': '30%',
        '7/10': '70%',
        '13/20': '65%',
        'marketing-container': 'min(1400px, calc(100% - 48px))',
        'marketing-container-mobile': 'min(100% - 32px, 640px)',
        'video-carousel': 'min(940px, 86vw)',
        'register-form': 'min(720px, 100%)',
        'mobile-sidebar': 'min(320px, 82vw)',
        'store-map-art': '800px',
      },
      maxWidth: {
        'gallery-grid': '1444px',
        marketing: '1400px',
        'marketing-title': '1240px',
        'news-list': '1280px',
        'store-map': '1180px',
        header: '1420px',
        'customer-logo': '132px',
        'pin-modal': '80vw',
        'pin-modal-sm': '30vw',
      },
      maxHeight: {
        'customer-logo': '58px',
      },
      minHeight: {
        'difference-panel': '900px',
        'franchise-service-card': '485px',
        'info-card': '300px',
        'info-card-compact': '235px',
        'service-concept': '1180px',
        'news-card': '728px',
        'customer-logo': '124px',
        timeline: '240px',
        'video-section': '560px',
        'store-map': '620px',
      },
      gridTemplateColumns: {
        footer: '220px 1fr',
        'footer-contact': '26px 1fr',
        header: '150px minmax(0, 1fr)',
        'header-tablet': '140px 1fr 42px',
        'header-phone': '112px 1fr 42px',
        hero: '240px minmax(0, 1320px) 240px',
        difference: '45fr 32fr',
        'story-panel': '580px minmax(0, 790px)',
        'store-map': '360px minmax(0, 1fr)',
      },
      gridTemplateRows: {
        header: '86px 90px',
        single: '1fr',
        opportunity: 'auto 1fr',
      },
      boxShadow: {
        navbar: '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
        box: '0 5px 10px 0px rgba(0, 0, 0, 0.2)',
        'brand-outline': '0 0 0 1px #d9d9d9',
        'brand-hairline': '0 1px 0 rgba(0,0,0,0.04)',
      },
      keyframes: {
        'scale-pulse': {
          '0%, 100%': { transform: 'scale(1, 1)' },
          '50%': { transform: 'scale(1.1, 1.1)' },
        },
        'tilt-shaking': {
          '0%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(5deg)' },
          '50%': { transform: 'rotate(0eg)' },
          '75%': { transform: 'rotate(-5deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        'tilt-n-move-shaking': {
          '0%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(5px, 5px) rotate(5deg)' },
          '50%': { transform: 'translate(0, 0) rotate(0eg)' },
          '75%': { transform: 'translate(-5px, 5px) rotate(-5deg)' },
          '100%': { transform: 'translate(0, 0) rotate(0deg)' },
        },
      },
      animation: {
        'scale-pulse': 'scale-pulse 1s linear infinite',
        'tilt-shaking': 'tilt-shaking 0.5s linear infinite',
        'tilt-n-move-shaking': 'tilt-n-move-shaking 0.5s linear infinite',
      },
      screens: {
        'less-sm': { max: '639px' },
        tablet: { max: '1180px' },
        map: { max: '900px' },
        phone: { max: '768px' },
      },
    },
  },
};
