export const APP_CONTENT_ID = 'app-content';
export const HOME_PAGE_SECTIONS = {
  BANNER_SLIDER: 'BANNER_SLIDER',
  INTRODUCTION: 'INTRODUCTION',
  ENSURE_OPPORTUNITY: 'ENSURE_OPPORTUNITY',
  STRENGTH_OF_FUN: 'STRENGTH_OF_FUN',
  SERVICES: 'SERVICES',
  CUSTOMER_TALK_ABOUT_US: 'CUSTOMER_TALK_ABOUT_US',
  COOPERATION_PROCESS: 'COOPERATION_PROCESS',
  FUN_STORES: 'FUN_STORES',
};
